// Structure OS agent definitions — the six DigiBi agents that absorb the 22
// n8n workflows into judgment layers. The AgentConsolePage renders these.
// Streams and approvals are seeded here for now; they'll come from the same
// n8n Owner Dashboard API once the agent-orchestration side is wired.

export const AGENT_ACCENT = {
  orchestrator: "#FB923C",
  content:      "#A78BFA",
  marketing:    "#F472B6",
  sales:        "#3B82F6",
  success:      "#10B981",
  finance:      "#F59E0B",
  product:      "#22D3EE",
  operations:   "#64748B",
  people:       "#F43F5E",
  strategy:     "#6366F1",
};

// Sub-agents (department functions) shown in each agent's detail. Status is
// good | warn | idle. This is the org depth surfaced in the Company OS — every
// department is really a small team of specialist functions.
export const SUB_AGENTS = {
  orchestrator: [
    { name: "Goal Planning", status: "good" },
    { name: "Prioritisation", status: "good" },
    { name: "Cross-dept Routing", status: "good" },
    { name: "Owner Digest", status: "good" },
  ],
  content: [
    { name: "Angle Research", status: "good" },
    { name: "Scripting", status: "good" },
    { name: "Rendering", status: "good" },
    { name: "Cross-posting", status: "good" },
  ],
  marketing: [
    { name: "Market Research", status: "good" },
    { name: "Competitor Intel", status: "warn" },
    { name: "Demand Gen", status: "warn" },
    { name: "Brand & Content", status: "good" },
    { name: "Lifecycle / CRM", status: "good" },
  ],
  sales: [
    { name: "Lead Generation", status: "good" },
    { name: "Qualification (SDR)", status: "good" },
    { name: "Account Executives", status: "good" },
    { name: "Sales Ops", status: "good" },
    { name: "Partnerships", status: "warn" },
  ],
  success: [
    { name: "Onboarding", status: "good" },
    { name: "QA / Call Scoring", status: "good" },
    { name: "Retention", status: "good" },
    { name: "Support", status: "good" },
    { name: "Reviews & Referrals", status: "good" },
  ],
  finance: [
    { name: "FP&A", status: "good" },
    { name: "Accounting", status: "good" },
    { name: "Billing & Collections", status: "warn" },
    { name: "Treasury", status: "good" },
    { name: "Tax & Compliance", status: "idle" },
  ],
  product: [
    { name: "Roadmap", status: "good" },
    { name: "Agent Engineering", status: "good" },
    { name: "Voice / Model Ops", status: "good" },
    { name: "QA & Eval", status: "good" },
  ],
  operations: [
    { name: "Provisioning", status: "good" },
    { name: "Infra & Vendors", status: "good" },
    { name: "Security", status: "warn" },
    { name: "Data Platform", status: "good" },
  ],
  people: [
    { name: "Recruiting", status: "idle" },
    { name: "Culture", status: "good" },
    { name: "Enablement", status: "good" },
  ],
  strategy: [
    { name: "Market Sizing", status: "warn" },
    { name: "Corp Dev", status: "idle" },
    { name: "New Verticals", status: "warn" },
    { name: "Investor Relations", status: "good" },
  ],
};

export const AGENTS = [
  {
    id: "orchestrator",
    name: "Chief of Staff",
    role: "Orchestration",
    lead: null,
    contribution: null,
    status: "idle",
    statusLabel: "Idle · next run 07:00",
    tagline: "Turns your one goal into the day's plan, watches for anything that needs you.",
    metricLabel: "Active goals",
    metricValue: "1",
    pipeline: [
      { name: "Parse goal", desc: "Break \"20 demos in June\" into department objectives." },
      { name: "Draft strategy", desc: "Route sub-goals to Sales · Marketing · Client Success · Finance." },
      { name: "Human review", desc: "You approve or edit the plan before agents move.", gate: true },
      { name: "Dispatch tasks", desc: "Push tasks to department agents; watch the event stream." },
      { name: "Daily digest", desc: "Roll goal progress + pending approvals into 07:00 owner email." },
    ],
    absorbs: [
      { name: "Daily Owner Digest", why: "One roll-up email replaces every department's own alerts." },
      { name: "Monthly Owner Report", why: "MRR / active clients / pipeline health rollup." },
    ],
    tools: ["supabase.events (read all)", "hubspot.pipeline_snapshot", "digest_email(hello@digi-bi.com)"],
  },
  {
    id: "content",
    name: "Content",
    role: "Video generation · social publishing",
    lead: "Nova",
    contribution: 66,
    status: "running",
    statusLabel: "Rendering today's video",
    tagline: "Ships a branded vertical video every day, picks the angle before it burns Higgsfield credits.",
    metricLabel: "Videos this week",
    metricValue: "5",
    pipeline: [
      { name: "Pick angle", desc: "Which trade / pain point / call scenario resonates today." },
      { name: "Draft brief", desc: "Hook + shot list + caption + hashtag set for the whole cross-post." },
      { name: "Human review", desc: "You approve the brief before Higgsfield renders (auto-skip when trusted).", gate: true },
      { name: "Render", desc: "Higgsfield builds the vertical explainer, DigiBi-branded." },
      { name: "Cross-post", desc: "One send → FB · IG · YouTube Shorts · TikTok with the caption." },
    ],
    absorbs: [
      { name: "Daily Video Generator & Poster", why: "Agent chooses topic; existing publish nodes stay as-is." },
    ],
    tools: ["higgsfield.generate_video", "fb_graph.post_reel", "ig_graph.post_reel", "youtube.upload_short", "tiktok.publish"],
  },
  {
    id: "marketing",
    name: "Marketing · Ads",
    role: "Meta ads · attribution · retargeting",
    lead: "Muse",
    contribution: 61,
    status: "pending",
    statusLabel: "1 approval waiting",
    tagline: "Reads the numbers, tells you what to change, and only spends on your say-so.",
    metricLabel: "MTD spend",
    metricValue: "R14,220",
    pipeline: [
      { name: "Pull insights", desc: "Meta campaign spend · impressions · clicks · leads for yesterday." },
      { name: "Compute pacing", desc: "MTD spend vs monthly ZAR budget · projection to month-end." },
      { name: "Diagnose", desc: "Flag spend-with-zero-leads campaigns; spot winners by CPL." },
      { name: "Recommend", desc: "Draft budget moves — scale winners, pause losers." },
      { name: "Human gate", desc: "You approve any budget move > ±20 % or an ad-set kill.", gate: true },
      { name: "Apply", desc: "Push budget / status changes to Meta; sync retargeting audience." },
      { name: "Attribution", desc: "Weekly: blend Meta spend with HubSpot deals, email the report." },
    ],
    absorbs: [
      { name: "Ads Performance Digest", why: "Interpret yesterday's CTR / CPC / CPL and pacing." },
      { name: "Lead Attribution Report", why: "Meta spend × HubSpot deals, weekly summary." },
      { name: "Retargeting Audience Sync", why: "Choose which active-lead cohorts get synced." },
    ],
    tools: ["meta_graph.insights", "meta_graph.update_adset", "meta_graph.custom_audience", "hubspot.search_deals", "email_send"],
  },
  {
    id: "sales",
    name: "Sales",
    role: "Intake · nurture · deal progression",
    lead: "Rex",
    contribution: 88,
    status: "running",
    statusLabel: "Drafting nurture batch",
    tagline: "Every DigiBi lead treated the same way, all day — from web-form to closed deal.",
    metricLabel: "Leads in flight",
    metricValue: "38",
    pipeline: [
      { name: "Ingest lead", desc: "Web form → HubSpot contact with digibi_lead_status." },
      { name: "Classify intent", desc: "Sales-fit or FAQ? Dispatch the matching Retell agent." },
      { name: "Find stale", desc: "Daily: leads > 3 days inactive, under 3-touch cap." },
      { name: "Personalize", desc: "Reference pain-point + industry; vary angle by touch 1 / 2 / 3." },
      { name: "Human gate", desc: "You approve every outbound before it sends.", gate: true },
      { name: "Send & track", desc: "digibi_nurture_count++; flip to unresponsive at 3." },
      { name: "Progress deals", desc: "Post-consult: move stage, draft proposal, gate the send." },
    ],
    absorbs: [
      { name: "Web Lead Intake", why: "Classify + dispatch to the right Retell agent." },
      { name: "Cold-Lead Nurture", why: "Personalized 3-touch, no more script-y drips." },
      { name: "Post-Consultation Deal Progression", why: "Move stage; draft the proposal email." },
      { name: "Call Retry Dispatcher", why: "When to redial an unreached call." },
      { name: "Consultation Config Capture", why: "Form input → HubSpot deal task." },
    ],
    tools: ["hubspot.contacts_search", "hubspot.contacts_update", "retell.dispatch_call", "email_send(sales@digi-bi.com)", "whatsapp.send"],
  },
  {
    id: "success",
    name: "Client Success",
    role: "Onboarding · QA · retention",
    lead: "Iris",
    contribution: 81,
    status: "running",
    statusLabel: "Scoring live calls",
    tagline: "Owns every client after payment lands — QA on every call, review asks, onboarding.",
    metricLabel: "Calls scored today",
    metricValue: "17",
    pipeline: [
      { name: "Ingest call", desc: "Retell webhook on every completed call." },
      { name: "Score", desc: "1–5 · sentiment · resolved? · issues[] · one-line summary." },
      { name: "Write back", desc: "digibi_last_call_score / sentiment / summary → HubSpot." },
      { name: "Flag low", desc: "Score ≤ 2 → owner Slack ping with call_id + issues." },
      { name: "Ask for review", desc: "Daily: happy clients (recent positive) → WhatsApp review + referral ask." },
      { name: "Human gate", desc: "You approve any personalized message before send.", gate: true },
      { name: "Onboard new", desc: "On close: checklist · portal user · set-password email." },
    ],
    absorbs: [
      { name: "Call-QA Scorer", why: "Grade every Retell call; escalate poor calls." },
      { name: "Reviews + Referrals", why: "Pick who to ask; write the personalized WhatsApp." },
      { name: "Onboarding Kickoff", why: "Sequence the whole first-week checklist." },
    ],
    tools: ["hubspot.contacts_update", "slack.post_owner", "whatsapp.send", "portal.provision_user"],
  },
  {
    id: "finance",
    name: "Finance",
    role: "Metered billing · dunning · provisioning",
    lead: "Athena",
    contribution: 74,
    status: "pending",
    statusLabel: "1 dunning sequence waiting",
    tagline: "Keeps ZAR moving; chases what doesn't, but not before you sign off on the escalation.",
    metricLabel: "MRR",
    metricValue: "R48,300",
    pipeline: [
      { name: "Daily meter", desc: "Per-client overage minutes → ZAR charges." },
      { name: "Anomaly check", desc: "Missing rate cards · usage spikes · near-limit accounts." },
      { name: "Charge or hold", desc: "Paystack charge on clean records; hold + alert on anomalies." },
      { name: "Dunning", desc: "Failed payment > 7 days → queue Retell billing call." },
      { name: "Human gate", desc: "You approve any dunning-call sequence before it dials.", gate: true },
      { name: "Provision", desc: "On payment success: create Retell agent + number, flip HubSpot stage." },
    ],
    absorbs: [
      { name: "Usage Reporting (Paystack)", why: "Interpret usage anomalies; flag missing rate cards." },
      { name: "Dunning Check", why: "Decide how hard to push, when to escalate." },
      { name: "Auto-Provisioning judgment", why: "Sanity-check payment → new Retell agent before executing." },
    ],
    tools: ["paystack.charge", "paystack.subscription", "retell.create_agent", "retell.buy_number", "hubspot.contacts_update"],
  },
  {
    id: "product",
    name: "Product & R&D",
    role: "Roadmap · agent engineering · voice ops",
    lead: "Vertex",
    contribution: 70,
    status: "running",
    statusLabel: "Shipping multilingual voice v2",
    tagline: "Builds and hardens the AI agents themselves — the product every client runs on.",
    metricLabel: "Uptime",
    metricValue: "99.94%",
    pipeline: [
      { name: "Prioritise roadmap", desc: "Rank what to build next against client pull + the North Star." },
      { name: "Build / iterate", desc: "Extend an agent's prompt, tools, or voice; branch it safely." },
      { name: "Eval & regression", desc: "Run the eval suite across all 6 client-facing agents before release." },
      { name: "Human gate", desc: "You approve any release that touches live client agents.", gate: true },
      { name: "Deploy", desc: "Roll the change to staging, then production behind a flag." },
      { name: "Monitor", desc: "Watch uptime, latency and failure rate; roll back on regression." },
    ],
    absorbs: [
      { name: "Agent QA & Eval suite", why: "Grade agent responses; block a regression before it ships." },
      { name: "Voice / Model Ops", why: "Pick model + voice per client; manage version pinning." },
      { name: "Release notes", why: "Summarise what changed for the owner + client portal." },
    ],
    tools: ["repo.read", "eval.run", "retell.update_agent", "slack.post_owner"],
  },
  {
    id: "operations",
    name: "Operations",
    role: "Provisioning · infra · security",
    lead: "Atlas",
    contribution: 76,
    status: "running",
    statusLabel: "Provisioned 6 clients overnight",
    tagline: "Keeps the lights on — provisions every client, watches infra and vendor spend, guards data.",
    metricLabel: "Provision SLA",
    metricValue: "< 5 min",
    pipeline: [
      { name: "Watch queue", desc: "Payment-success events waiting to be provisioned." },
      { name: "Provision", desc: "Create the Retell agent + number, wire the webhooks." },
      { name: "Verify", desc: "Test call + health check before handing to Client Success." },
      { name: "Human gate", desc: "You approve anything anomalous — duplicate, refund, odd region.", gate: true },
      { name: "Vendor / cost check", desc: "Daily: infra + vendor spend vs budget; flag overruns." },
      { name: "Incident watch", desc: "Uptime + error-rate monitor; page the owner on a real incident." },
    ],
    absorbs: [
      { name: "Auto-Provisioning (ops)", why: "Own the provision → verify → handoff path end to end." },
      { name: "Vendor Spend Watch", why: "Catch a runaway API bill before month-end." },
      { name: "Uptime & Security Monitor", why: "One eye on infra health + access, always." },
    ],
    tools: ["retell.create_agent", "retell.buy_number", "hubspot.contacts_update", "slack.post_owner"],
  },
  {
    id: "people",
    name: "People & Talent",
    role: "Recruiting · culture · enablement",
    lead: "Sage",
    contribution: 44,
    status: "idle",
    statusLabel: "Standby · no open reqs",
    tagline: "Scales the team — human and agent — through hiring, enablement and the playbooks agents run on.",
    metricLabel: "Agent enablement",
    metricValue: "92%",
    pipeline: [
      { name: "Track the plan", desc: "Headcount + agent-capability plan against the North Star." },
      { name: "Source", desc: "When a req opens: find and shortlist candidates." },
      { name: "Screen", desc: "First-pass screen + schedule; keep the pipeline moving." },
      { name: "Human gate", desc: "You approve every offer before it goes out.", gate: true },
      { name: "Onboard", desc: "First-week checklist for a new hire or a new agent role." },
      { name: "Refresh enablement", desc: "Keep the playbooks the other agents run on current." },
    ],
    absorbs: [
      { name: "Enablement Playbooks", why: "The living docs every department agent is prompted from." },
      { name: "Culture Pulse", why: "Lightweight check on how the team (and its agents) are running." },
    ],
    tools: ["hubspot.notes", "email_send", "slack.post_owner"],
  },
  {
    id: "strategy",
    name: "Strategy & BizDev",
    role: "Market research · corp dev · expansion",
    lead: "Oracle",
    contribution: 58,
    status: "pending",
    statusLabel: "UK expansion scoping",
    tagline: "Points the whole company at the biggest opportunity — market sizing, new verticals, partnerships.",
    metricLabel: "New markets",
    metricValue: "3 scoped",
    pipeline: [
      { name: "Scan", desc: "Watch the market, adjacent verticals and rival moves for openings." },
      { name: "Size", desc: "Model TAM / reachable revenue for a new market or vertical." },
      { name: "Teardown", desc: "Strategic competitor teardown (feeds Marketing's ad-level intel)." },
      { name: "Human gate", desc: "You make the go / no-go on any new-market bet.", gate: true },
      { name: "Draft plan", desc: "Entry plan: pricing, regulatory, first-10-clients motion." },
      { name: "Track thesis", desc: "Keep each expansion thesis honest against real results." },
    ],
    absorbs: [
      { name: "Market Sizing", why: "Turn a hunch into a defensible TAM number." },
      { name: "Strategic Competitor Intel", why: "Company-level moves (Marketing owns ad/creative intel)." },
      { name: "Investor / Owner Updates", why: "Roll the strategy view into a monthly narrative." },
    ],
    tools: ["hubspot.search_deals", "web.research", "email_send", "slack.post_owner"],
  },
];

// Approvals and events live in Supabase now — the Agent Console fetches them
// via /api/approvals and /api/agent-events. Nothing seeded here.
